import type { FabricAgent } from "@/features/agent-fabric/types/agentFabricTypes";

export const fabricAgents: FabricAgent[] = Object.freeze([
  {
    id: "fabric-agent-shipment-intelligence",
    type: "shipment_intelligence",
    label: "Shipment intelligence agent",
    capabilities: ["shipment_monitoring", "customer_follow_up", "anomaly_triage"],
    deterministic: true,
    approvalAware: true,
    maxConcurrentDelegations: 4,
    priorityBias: 8,
  },
  {
    id: "fabric-agent-escalation-coordination",
    type: "escalation_coordination",
    label: "Escalation coordination agent",
    capabilities: ["escalation_recovery", "customer_follow_up", "executive_briefing"],
    deterministic: true,
    approvalAware: true,
    maxConcurrentDelegations: 3,
    priorityBias: 10,
  },
  {
    id: "fabric-agent-finance-supervision",
    type: "finance_supervision",
    label: "Finance supervision agent",
    capabilities: ["finance_review", "execution_guarding", "executive_briefing"],
    deterministic: true,
    approvalAware: true,
    maxConcurrentDelegations: 3,
    priorityBias: 9,
  },
  {
    id: "fabric-agent-workflow-recovery",
    type: "workflow_recovery",
    label: "Workflow recovery agent",
    capabilities: ["workflow_optimization", "escalation_recovery", "execution_guarding"],
    deterministic: true,
    approvalAware: true,
    maxConcurrentDelegations: 4,
    priorityBias: 7,
  },
  {
    id: "fabric-agent-customer-operations",
    type: "customer_operations",
    label: "Customer operations agent",
    capabilities: ["customer_follow_up", "shipment_monitoring"],
    deterministic: true,
    approvalAware: true,
    maxConcurrentDelegations: 5,
    priorityBias: 4,
  },
  {
    id: "fabric-agent-executive-oversight",
    type: "executive_oversight",
    label: "Executive oversight agent",
    capabilities: ["executive_briefing", "finance_review", "escalation_recovery"],
    deterministic: true,
    approvalAware: true,
    maxConcurrentDelegations: 2,
    priorityBias: 11,
  },
  {
    id: "fabric-agent-operational-anomaly-analysis",
    type: "operational_anomaly_analysis",
    label: "Operational anomaly analysis agent",
    capabilities: ["anomaly_triage", "workflow_optimization", "shipment_monitoring"],
    deterministic: true,
    approvalAware: true,
    maxConcurrentDelegations: 4,
    priorityBias: 6,
  },
  {
    id: "fabric-agent-execution-supervision",
    type: "execution_supervision",
    label: "Execution supervision agent",
    capabilities: ["execution_guarding", "executive_briefing", "finance_review"],
    deterministic: true,
    approvalAware: true,
    maxConcurrentDelegations: 3,
    priorityBias: 12,
  },
]);

export const getFabricAgentById = (agentId: string) => fabricAgents.find((agent) => agent.id === agentId);
