import { cognitiveReasoningPolicy, priorityFromSeverity, severityFromScore } from "@/features/cognitive-ops/reasoning/reasoningPolicies";
import { recallOperationalMemory } from "@/features/cognitive-ops/memory/operationalMemory";
import type {
  OperationalContextSnapshot,
  OperationalMemoryRecord,
  ReasoningFinding,
  ReasoningKind,
} from "@/features/cognitive-ops/types/cognitiveTypes";
import type { WorkflowSeverity } from "@/features/workflow-intelligence/types/workflowTypes";

const findingId = (kind: ReasoningKind, entityId: string, replayBasis: string) =>
  `reason-${kind}-${entityId}-${replayBasis.replace(/[^a-zA-Z0-9-]/g, "-").slice(0, 36)}`;

const makeFinding = ({
  kind,
  severity,
  entityType,
  entityId,
  label,
  title,
  explanation,
  recommendation,
  replayKeys,
  approvalRequired,
  score,
  createdAt,
}: {
  kind: ReasoningKind;
  severity: WorkflowSeverity;
  entityType: ReasoningFinding["entity"]["entityType"];
  entityId: string;
  label: string;
  title: string;
  explanation: string;
  recommendation: string;
  replayKeys: string[];
  approvalRequired: boolean;
  score: number;
  createdAt: string;
}): ReasoningFinding =>
  Object.freeze({
    id: findingId(kind, entityId, replayKeys[0] || createdAt),
    kind,
    severity,
    priority: priorityFromSeverity(severity) + Math.min(20, replayKeys.length * 2),
    entity: Object.freeze({ entityType, entityId, label }),
    title,
    explanation,
    recommendation,
    evidenceReplayKeys: Object.freeze([...replayKeys]) as string[],
    approvalRequired,
    deterministicScore: score,
    createdAt,
    immutable: true,
  });

export const runContextualReasoning = (
  context: OperationalContextSnapshot,
  memory: OperationalMemoryRecord[],
): ReasoningFinding[] => {
  const createdAt = context.generatedAt;
  const findings: ReasoningFinding[] = [];

  context.workflow.triggers.forEach((trigger) => {
    const recalled = recallOperationalMemory(memory, { entityId: trigger.entityId, limit: 6 });
    const score = priorityFromSeverity(trigger.severity) + Math.min(15, trigger.ageDays) + Math.min(10, recalled.length * 2);
    const kind: ReasoningKind =
      trigger.type === "financial_risk_spike"
        ? "finance_anomaly"
        : trigger.type === "stalled_workflow_stage" || trigger.type === "missing_update"
          ? "workflow_bottleneck"
          : trigger.type.includes("escalation") || trigger.type === "unresolved_dispute"
            ? "escalation"
            : "operational_risk";

    findings.push(
      makeFinding({
        kind,
        severity: severityFromScore(score),
        entityType: trigger.entityType,
        entityId: trigger.entityId,
        label: trigger.entityLabel,
        title: `${trigger.entityLabel}: ${trigger.type.replaceAll("_", " ")}`,
        explanation: `${trigger.reasons.join("; ")}. Memory recall found ${recalled.length} related immutable records.`,
        recommendation: trigger.suggestedFollowUp,
        replayKeys: recalled.map((record) => record.replayKey),
        approvalRequired: trigger.severity === "critical" || trigger.financialExposure >= cognitiveReasoningPolicy.financeAnomalyAmount,
        score,
        createdAt,
      }),
    );
  });

  context.execution.queue.forEach((item) => {
    if (item.status !== "approval_required" && item.action.priority !== "critical") return;
    const recalled = recallOperationalMemory(memory, { entityId: item.action.id, limit: 4 });
    const score = item.action.priority === "critical" ? 94 : 72;

    findings.push(
      makeFinding({
        kind: "execution_impact",
        severity: severityFromScore(score),
        entityType: item.action.entity.entityType,
        entityId: item.action.entity.entityId,
        label: item.action.entity.label,
        title: item.action.title,
        explanation: `${item.status} execution item generated by ${item.action.agentType}; approval and replay key controls are active.`,
        recommendation: item.action.detail,
        replayKeys: [item.action.replayKey, ...recalled.map((record) => record.replayKey)],
        approvalRequired: item.action.approvalRequired,
        score,
        createdAt,
      }),
    );
  });

  const prioritizedEntities = new Map<string, ReasoningFinding[]>();
  findings.forEach((finding) => {
    const bucket = prioritizedEntities.get(finding.entity.entityId) || [];
    bucket.push(finding);
    prioritizedEntities.set(finding.entity.entityId, bucket);
  });

  prioritizedEntities.forEach((entityFindings, entityId) => {
    if (entityFindings.length < 2) return;
    const top = [...entityFindings].sort((first, second) => second.priority - first.priority)[0];
    findings.push(
      makeFinding({
        kind: "operational_prioritization",
        severity: top.severity,
        entityType: top.entity.entityType,
        entityId,
        label: top.entity.label,
        title: `Prioritize ${top.entity.label}`,
        explanation: `${entityFindings.length} independent cognitive signals point to the same operational entity.`,
        recommendation: "Review the highest severity recommendation first, then sequence follow-ups through approval-aware plans.",
        replayKeys: entityFindings.flatMap((finding) => finding.evidenceReplayKeys).slice(0, 8),
        approvalRequired: entityFindings.some((finding) => finding.approvalRequired),
        score: Math.min(100, top.deterministicScore + entityFindings.length * 4),
        createdAt,
      }),
    );
  });

  return findings
    .sort((first, second) => second.priority - first.priority || first.id.localeCompare(second.id))
    .slice(0, cognitiveReasoningPolicy.maxFindings);
};
